### ISSUE TITLE
Detect all variations of Dockerfiles in docker-compose

### ISSUE THREAD

**Issue by j-maas** [Y0hy0h/updock#8]
docker-compose has four notations that should be handled by updock:

- The [`build`](https://docs.docker.com/compose/compose-file/#build) field can be
  - a string specifying a directory containing a Dockerfile,
  - a struct containing just a context path (which might be a URL to a Git repo),
  - a struct containing the a context path and a Dockerfile name,
- The [`image`](https://docs.docker.com/compose/compose-file/#image) field, without a `build` field, can contain an image and tag to pull.

**Comment by j-maas** [comment]
While we can parse the `docker-compose.yml` into a structured representation for the `build` variants, we would need to keep the comments that indicate the pattern for the `image` variant which `serde_yaml` does not do.

An alternative is [`marked-yaml`](https://crates.io/crates/marked-yaml), which gives us the line numbers. If we require the pattern annotation to be in the preceding line, it is easy to find it.

**Comment by Y0hy0h** [comment]
A simple workaround would be to ignore all unsupported variants and report how many services were ignored.
